---
title: "DSA 554 3.0 Spatio-temporal Data Analysis"
---

## Lecture 1: November 30, 2024

[Slides 1](/Week1/index.html)

## Lecture 2: December 7, 2024

[Slides 2](/Week2/index.html)

[Practical 1](https://thiyangt.github.io/spts_python_practical/Practical1/)

## Public Holiday: December 14, 2024

## Lecture 3: December 21, 2024

[Slides 3](/Week3/index.html)

[Practical 2](/Week3p/index.html)

[Practical 3](/Week3p2/index.html)

[Slides 4](https://thiyanga-spatiotemporal.netlify.app/posts/spatial/spatial_analysis.pdf)

## Lecture 4: 4 January 2025

[Slides 5](https://thiyanga-dataviz.netlify.app/slides/sp_viz#1)

<!--[Slides 5](https://thiyangt.github.io/spatial-modelling/#/outline)-->

[Practical 4 - With R](/Week4p/index.R)

[Practical 5 - With Python](/Week4p2/index.html)

## Lecture 5: 11 Jan 2025

[Practical 6 - With python](/Week5/index.html)

[Data 1](/Week5/datasets/us-states.json)

[Data 2](/Week5/datasets/world-happiness-report-2019.csv)

[Practical 7 - With R](http://lab.rady.ucsd.edu/sawtooth/RAnalytics/maps.html)

[Slides 6](https://thiyangt.github.io/spatial-modelling/#/title-slide)

## Lecture 6: 25 Jan 2025

[Variogram Calculation - Excel File](https://github.com/GeostatsGuy/GeoDataSets/blob/master/1D_Porosity.xlsx)

Acknowledgement for data: Prof Michael Pyrcz, Full Professor at The University of Texas at Austin working on Spatial Data Analytics, Geostatistics and Machine Learning. Link: https://github.com/GeostatsGuy

[Slides 7](/Week6/index.html)

[Reading](https://csegrecorder.com/articles/view/the-variogram-basics-a-visual-intro-to-useful-geostatistical-concepts)

## Lecture 7: 1 February 2025

Kriging: Continue from Slides 6 and Slides 7

Task: Find a suitable kriging model to interpolate zinc concentration in meuse dataset.

[Spatial interpolation with Python](https://scikit-gstat.readthedocs.io/en/latest/userguide/kriging.html)

[SciKit-GStat 1.0: a SciPy-flavored geostatistical variogram estimation toolbox written in Python](https://gmd.copernicus.org/articles/15/2505/2022/gmd-15-2505-2022.html)

[Reading - Modelling with trend](https://geostatisticslessons.com/lessons/trendmodeling)

## Lecture 8: 8 February 2025

Interpolation of meuse dataset and NO2 data sets.

cross validation approaches in spatial data analysis - cont. slide 7

Which variogram model to use: [read here](https://csegrecorder.com/articles/view/the-variogram-basics-a-visual-intro-to-useful-geostatistical-concepts)

# Additional reading

[Introduction to Kriging with R](https://dickbrus.github.io/SpatialSamplingwithR/Introkriging.html)

# Papers to read

Feature-based learning

-   [Incorporating Spatial Autocorrelation in Machine Learning Models Using Spatial Lag and Eigenvector Spatial Filtering Features](https://www.mdpi.com/2220-9964/11/4/242)
